ref #4 configuration of the workflow
- schedule to run it everday
- run the build scripts
- install graphviz so its possible to generate the svg files
- commit and push the svg changes
- upload the log of the commands used

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -1,34 +1,51 @@
-# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
-
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-
 name: Java CI with Maven
 
 on:
-  push:
-    branches:
-      - master    
-#  workflow_dispatch:
+  schedule:
+    - cron: '0 0 * * *' # every day at 00:00
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
-    steps:
-    - uses: actions/checkout@v3
+    steps: 
+    - name: Get the code from the repository
+      uses: actions/checkout@v3
       with:
         ref: 'master'
-        fetch-depth: 0
-      
+        fetch-depth: 0 
+
     - name: Set up JDK 11
-      uses: actions/setup-java@v3
+      uses: actions/setup-java@v2
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: maven
+    # Give execute permissions to the build scripts
+    #- name: Set execute permissions on build scripts
+    #  run: chmod +x bin/build-all.sh bin/quickbuild.sh bin/generate-plantuml-diagrams.sh || true
 
+    - name: Full build with Maven
+      run: ./bin/build-all.sh 2> error-logs/build-all.log || true
+    - name: Quick build with Maven
+      run: ./bin/quickbuild.sh 2> error-logs/quickbuild.log || true
+    
+    - name: Upload error logs
+      uses: actions/upload-artifact@v2
+      if: always() # This ensures that logs are uploaded even if previous step fails
+      with:
+        name: error-logs
+        path: error-logs/
+
+    - name: Install Graphviz
+      run: sudo apt-get install -y graphviz
+
+    - name: Update .svg
+      run: ./bin/generate-plantuml-diagrams.sh
+
+    - name: Commit and push changes
+      run: |
+        git config --global user.name "github-actions[bot]"
+        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+        git add .
+        git diff --quiet && git diff --staged --quiet || (git commit -m "Update diagrams"; git push origin HEAD:master)
